// Code generated by "stringer -type=statType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DiveLength-0]
	_ = x[Buddies-1]
	_ = x[Cylinders-2]
	_ = x[MeanDepth-3]
	_ = x[MaxDepth-4]
	_ = x[Temperature-5]
	_ = x[DiveSite-6]
}

const _statType_name = "DiveLengthBuddiesCylindersMeanDepthMaxDepthTemperatureDiveSite"

var _statType_index = [...]uint8{0, 10, 17, 26, 35, 43, 54, 62}

func (i statType) String() string {
	if i < 0 || i >= statType(len(_statType_index)-1) {
		return "statType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _statType_name[_statType_index[i]:_statType_index[i+1]]
}
